# File const
VALID_MAX_FILE_SIZE = 2097152
VALID_MAX_FILE_LENGTH_TEXT = 21000
VALID_MIN_FILE_LENGTH_TEXT = 50
VALID_EXTENSIONS_FILE = {"docx", "pdf", "txt"}
VALID_CONTENT_FILE = {"application/pdf", "application/zip", "text/plain"}

# API file const
API_VALID_MAX_FILE_SIZE = 2097152
API_VALID_MAX_FILE_LENGTH_TEXT = 5000
API_VALID_MIN_FILE_LENGTH_TEXT = 50
API_VALID_EXTENSIONS_FILE = VALID_EXTENSIONS_FILE
API_VALID_CONTENT_FILE = VALID_CONTENT_FILE

# Text const
VALID_MAX_FORM_LENGTH_TEXT = 1000
VALID_MIN_FORM_LENGTH_TEXT = 50

# API text const
API_VALID_MAX_FORM_LENGTH_TEXT = VALID_MAX_FORM_LENGTH_TEXT
API_VALID_MIN_FORM_LENGTH_TEXT = VALID_MIN_FORM_LENGTH_TEXT
