# Generated by Django 5.0.3 on 2024-03-29 10:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "created_add",
                    models.DateTimeField(
                        auto_created=True,
                        auto_now_add=True,
                        verbose_name="Время добавления",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "input_text",
                    models.TextField(max_length=10000, verbose_name="Введенный текст"),
                ),
                (
                    "result_text",
                    models.TextField(
                        max_length=10000, verbose_name="Результата обработки"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удален"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_add"],
                "indexes": [
                    models.Index(
                        fields=["created_add", "is_deleted"],
                        name="history_his_created_76cef1_idx",
                    )
                ],
            },
        ),
    ]
