# Generated by Django 5.0.3 on 2024-03-29 10:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0002_alter_history_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="History",
            new_name="HistoryModel",
        ),
        migrations.AlterModelOptions(
            name="historymodel",
            options={"ordering": ["-created_at"], "verbose_name_plural": "История"},
        ),
        migrations.RenameIndex(
            model_name="historymodel",
            new_name="history_his_created_86f56b_idx",
            old_name="history_his_created_f5630c_idx",
        ),
    ]
