# Generated by Django 5.0.2 on 2024-03-05 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanguagePoaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('poa_text', models.TextField(max_length=6000, validators=[django.core.validators.MinLengthValidator(3000)])),
            ],
            options={
                'ordering': ['language'],
                'indexes': [models.Index(fields=['language'], name='language_ap_languag_77a3ef_idx')],
            },
        ),
    ]
