# Generated by Django 5.0.3 on 2024-03-17 12:19

import api_key.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired_at', models.DateTimeField(auto_created=True, default=api_key.models.default_expired_at, verbose_name='Время истечения')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Время добавления')),
                ('api_token', models.CharField(default=api_key.models.generate_api_key, editable=False, unique=True, verbose_name='API ключ')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('is_expired', models.BooleanField(default=False, verbose_name='Истек')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['created_at', 'expired_at', 'is_deleted', 'is_expired'], name='api_key_api_created_d8d9c2_idx')],
            },
        ),
    ]
