# Generated by Django 5.0.3 on 2024-03-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_key", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikeymodel",
            name="api_token",
            field=models.CharField(
                editable=False, unique=True, verbose_name="API ключ"
            ),
        ),
    ]
