# Generated by Django 5.0.2 on 2024-03-10 19:06

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_key', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='apikeymodel',
            name='api_key_api_created_02ad2e_idx',
        ),
        migrations.AddField(
            model_name='apikeymodel',
            name='is_expired',
            field=models.BooleanField(default=False, verbose_name='Истек'),
        ),
        migrations.AlterField(
            model_name='apikeymodel',
            name='expired_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 3, 17, 19, 5, 57, 972713), editable=False, verbose_name='Время истечения'),
        ),
        migrations.AddIndex(
            model_name='apikeymodel',
            index=models.Index(fields=['created_at', 'expired_at', 'is_deleted', 'is_expired'], name='api_key_api_created_d8d9c2_idx'),
        ),
    ]
