# Generated by Django 5.0.3 on 2024-03-29 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_key", "0002_alter_apikeymodel_api_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apikeymodel",
            options={"ordering": ["created_at"], "verbose_name_plural": "API токены"},
        ),
    ]
